cards_list = [
    {"name": "Se soigner", "texte":"écriture", "health":20, "food": -25, "materials":-10, "relationship":0, "power":0, "repetable":True, "image":"images/card_picture/healthcard.jpg"},
    {"name": "Renforcer l'abri", "texte":"", "health":-10, "food": 0, "materials":-10, "relationship":10, "power":10 , "repetable":False, "image":"images/card_picture/placeholder.png"},
    {"name": "Trouver un point d'eau", "texte":"", "health":-10, "food": 25, "materials":-10, "relationship":0, "power":0 , "repetable":False, "image":"images/card_picture/foodcard.jpg"},
    {"name": "*Se suicider*", "texte":"écriture", "health":-70, "food": 50, "materials":50, "relationship":-50, "power":0, "repetable":False, "image":"images/card_picture/placeholder.png" },
    {"name": "Fabriquer des outils", "texte":"écriture", "health":-10, "food": -10, "materials":-10, "relationship":0, "power":15, "repetable":False, "image": "images/card_picture/powercard.jpg" },
    {"name": "Faire du feu", "texte":"écriture", "health":0, "food": 15, "materials":-10, "relationship":0, "power":0, "repetable":True, "image":"images/card_picture/foodcard.jpg" },
    {"name": "Explorer la foret", "texte":"écriture", "health":0, "food": 0, "materials":15, "relationship":0, "power":0, "repetable":None, "image":"images/card_picture/ressourcecard.jpg" },
    {"name": "Faire de l'agriculture", "texte":"écriture", "health":10, "food": 30, "materials":-20, "relationship":0, "power":0, "repetable":False, "image":"images/card_picture/foodcard.jpg" },
    {"name": "Fabriquer des armes", "texte":"écriture", "health":10, "food": 0, "materials":-20, "relationship":0, "power":15, "repetable":False, "image":"images/card_picture/powercard.jpg" },
    {"name": "Regarder les étoiles", "texte":"écriture", "health":0, "food": -10, "materials":0, "relationship":20, "power":0, "repetable":False, "image":"images/card_picture/relationshipcard.jpg" },
    {"name": "Explorer les grottes", "texte":"écriture", "health":-10, "food": 10, "materials":25, "relationship":0, "power":0, "repetable":True, "image":"images/card_picture/ressourcecard.jpg" },
    {"name": "Faire l'abri", "texte":"écriture", "health":20, "food":-10, "materials":-25, "relationship":10, "power":5, "repetable":False, "image":"images/card_picture/healthcard.jpg" },
    {"name": "Rassurer un survivant", "texte":"écriture", "health":10, "food": 0, "materials":0, "relationship":20, "power":0, "repetable":True, "image":"images/card_picture/relationshipcard.jpg" },
    {"name": "Construire un champ", "texte":"écriture", "health":10, "food": 20, "materials":-20, "relationship":0, "power":0, "repetable":False, "image":"images/card_picture/foodcard.jpg" },
    {"name": "Pêcher", "texte":"écriture", "health":0, "food": 25, "materials":10, "relationship":0, "power":0, "repetable":True, "image":"images/card_picture/foodcard.jpg" },
    {"name": "Dormir", "texte":"écriture", "health":20, "food": 0, "materials":0, "relationship":-10, "power":0, "repetable":True, "image":"images/card_picture/healthcard.jpg" },
    {"name": "*Instaurer une religion*", "texte":"écriture", "health":0, "food": 0, "materials":0, "relationship":-10, "power":10, "repetable":False, "image":"images/card_picture/relationshipcard.jpg" },
    {"name": "Faire des vêtements", "texte":"écriture", "health":20, "food": 0, "materials":-20, "relationship":0, "power":0, "repetable":False, "image":"images/card_picture/healthcard.jpg" },
    {"name": "Créer des cordes", "texte":"écriture", "health":0, "food": 0, "materials":10, "relationship":0, "power":0, "repetable":False, "image":"images/card_picture/ressourcecard.jpg" },
    {"name": "Disposer des pierres sur la plage", "texte":"écriture", "health":0, "food": 0, "materials":-20, "relationship":10, "power":0, "repetable":False, "image":"images/card_picture/relationshipcard.jpg" },
    {"name": "Lancer une bouteille à la mer", "texte":"écriture", "health":0, "food": 0, "materials":-10, "relationship":10, "power":0, "repetable":False, "image":"images/card_picture/relationshipcard.jpg" },
    {"name": "Construire un phare", "texte":"écriture", "health":10, "food": 0, "materials":-25, "relationship":20, "power":10, "repetable":False, "image":"images/card_picture/relationshipcard.jpg" },
    {"name": "*Executer les prisonniers*", "texte":"écriture", "health":0, "food": 0, "materials":10, "relationship":-20, "power":0, "repetable":False, "image":"images/card_picture/ressourcecard.jpg" },
    {"name": "Dépecer les animaux", "texte":"écriture", "health":-10, "food": 25, "materials":0, "relationship":-20, "power":0, "repetable":False, "image":"images/card_picture/foodcard.jpg" },
    {"name": "Fabriquer des gourdes", "texte":"écriture", "health":5, "food": 0, "materials":10, "relationship":0, "power":0, "repetable":False, "image":"images/card_picture/ressourcecard.jpg" },
    {"name": "Enterrer les animaux pour les conserver", "texte":"écriture", "health":10, "food": 10, "materials":-10, "relationship":-25, "power":0, "repetable":False, "image":"images/card_picture/placeholder.png" },
    {"name": "Fabriquer des bandages", "texte":"écriture", "health":20, "food": 0, "materials":-10, "relationship":0, "power":0, "repetable":False, "image":"images/card_picture/healthcard.jpg" },
    {"name": "Organiser un tournoi", "texte":"écriture", "health":-10, "food": 0, "materials":0, "relationship":20, "power":0, "repetable":False, "image":"images/card_picture/relationshipcard.jpg" },
    {"name": "Récolter des plantes", "texte":"écriture", "health":20, "food": 20, "materials":0, "relationship":0, "power":0, "repetable":False, "image":"images/card_picture/placeholder.png" },
    {"name": "S'entrainer", "texte":"écriture", "health":-10, "food": 0, "materials":0, "relationship":0, "power":0, "repetable":True, "image":"images/card_picture/placeholder.png" },
    {"name": "Jouer aux cartes", "texte":"écriture", "health":0, "food": 0, "materials":0, "relationship":10, "power":0, "repetable":True, "image":"images/card_picture/relationshipcard.jpg" },
    {"name": "Faire de la musique", "texte":"écriture", "health":0, "food": 0, "materials":0, "relationship":10, "power":0, "repetable":True, "image":"images/card_picture/relationshipcard.jpg" },
    {"name": "Apprivoiser un animal", "texte":"écriture", "health":-10, "food": 0, "materials":0, "relationship":20, "power":10, "repetable":False, "image":"images/card_picture/relationshipcard.jpg" },
    {"name": "Chasser en groupe", "texte":"écriture", "health":0, "food": 20, "materials":0, "relationship":10, "power":0, "repetable":True, "image":"images/card_picture/foodcard.jpg" },
    {"name": "Créer une cache de ressource", "texte":"écriture", "health":0, "food": -10, "materials":10, "relationship":0, "power":0, "repetable":False, "image":"images/card_picture/ressourcecard.jpg" },
    {"name": "*Cartographier l'île*", "texte":"écriture", "health":0, "food": 0, "materials":0, "relationship":0, "power":0, "repetable":True, "image":"images/card_picture/placeholder.png" },
    {"name": "Tester la nourriture", "texte":"écriture", "health":-10, "food": 10, "materials":0, "relationship":0, "power":0, "repetable":False, "image":"images/card_picture/foodcard.jpg" },
    {"name": "Monter à l'arbre", "texte":"écriture", "health":-5, "food": 0, "materials":0, "relationship":0, "power":0, "repetable":True, "image":"images/card_picture/relationshipcard.jpg" },
    {"name": "Couper du bois", "texte":"écriture", "health":-10, "food": 0, "materials":25, "relationship":0, "power":0, "repetable":True, "image":"images/card_picture/ressourcecard.jpg" },
    {"name": "Récolter des graines", "texte":"écriture", "health":10, "food": 20, "materials":0, "relationship":0, "power":0, "repetable":True, "image":"images/card_picture/foodcard.jpg" },
    {"name": "Récolter du sel", "texte":"écriture", "health":0, "food": 10, "materials":0, "relationship":10, "power":0, "repetable":True, "image":"images/card_picture/placeholder.png" },
    {"name": "Filtrer l'eau", "texte":"écriture", "health":10, "food": 10, "materials":-25, "relationship":0, "power":0, "repetable":False, "image":"images/card_picture/placeholder.png" },
    {"name": "Boire son urine", "texte":"écriture", "health":-10, "food": 10, "materials":0, "relationship":-10, "power":0, "repetable":True, "image":"images/card_picture/foodcard.jpg" },
    {"name": "Faire de la farine", "texte":"écriture", "health":0, "food": 10, "materials":0, "relationship":10, "power":0, "repetable":False, "image":"images/card_picture/placeholder.png" },
    {"name": "Récolter des cristaux", "texte":"écriture", "health":0, "food": 0, "materials":25, "relationship":0, "power":0, "repetable":True, "image":"images/card_picture/ressourcecard.jpg" },
    {"name": "Faire du rhum", "texte":"écriture", "health":10, "food": -10, "materials":0, "relationship":10, "power":0, "repetable":False, "image":"images/card_picture/placeholder.png" },
    {"name": "*Faire un sacrifice*", "texte":"écriture", "health":0, "food": 20, "materials":0, "relationship":-50, "power":-10, "repetable":False, "image":"images/card_picture/foodcard.jpg" },
    {"name": "*Créer un drapeau*", "texte":"écriture", "health":0, "food": 0, "materials":-10, "relationship":25, "power":0, "repetable":False, "image":"images/card_picture/relationshipcard.jpg" },
    {"name": "*Nommer la colonie*", "texte":"écriture", "health":0, "food": 0, "materials":0, "relationship":10, "power":0, "repetable":False, "image":"images/card_picture/relationshipcard.jpg" },
    {"name": "Créer un bouclier", "texte":"écriture", "health":0, "food": 0, "materials":-10, "relationship":10, "power":10, "repetable":False, "image":"images/card_picture/placeholder.png" },
    {"name": "Etudier la faune", "texte":"écriture", "health":-10, "food": 10, "materials":5, "relationship":0, "power":0, "repetable":False, "image":"images/card_picture/foodcard.jpg" },
    {"name": "Etudier la flore", "texte":"écriture", "health":10, "food": 0, "materials":0, "relationship":0, "power":0, "repetable":False, "image":"images/card_picture/healthcard.jpg" },
    {"name": "Fabriquer des pots en terre cuites", "texte":"écriture", "health":0, "food": 0, "materials":10, "relationship":0, "power":0, "repetable":False, "image":"images/card_picture/ressourcecard.jpg" },
    {"name": "Se baigner", "texte":"écriture", "health":10, "food": 0, "materials":0, "relationship":0, "power":0, "repetable":True, "image":"images/card_picture/healthcard.jpg" },
    {"name": "Organiser une course", "texte":"écriture", "health":0, "food": -10, "materials":0, "relationship":10, "power":0, "repetable":False, "image":"images/card_picture/relationshipcard.jpg" },
    {"name": "Construire un hamac", "texte":"écriture", "health":10, "food": 0, "materials":-10, "relationship":0, "power":0, "repetable":False, "image":"images/card_picture/healthcard.jpg" },
    {"name": "Préparer le repas", "texte":"écriture", "health":10, "food": 10, "materials":-10, "relationship":0, "power":0, "repetable":True, "image":"images/card_picture/placeholder.png" },
    {"name": "Organiser un pique-nique", "texte":"écriture", "health":0, "food": 10, "materials":-10, "relationship":0, "power":0, "repetable":True, "image":"images/card_picture/foodcard.jpg" },
    {"name": "Collectioner des coquillages", "texte":"écriture", "health":0, "food": 0, "materials":10, "relationship":0, "power":0, "repetable":True, "image":"images/card_picture/ressourcecard.jpg" },
    {"name": "Faire l'inventaire des ressources", "texte":"écriture", "health":0, "food": 0, "materials":10, "relationship":0, "power":0, "repetable":True, "image":"images/card_picture/ressourcecard.jpg" },
    {"name": "Débrousailler autour du camp", "texte":"écriture", "health":0, "food": 0, "materials":10, "relationship":0, "power":0, "repetable":False, "image":"images/card_picture/ressourcecard.jpg" },
    {"name": "Fouiller autour du camp", "texte":"écriture", "health":0, "food": 0, "materials":10, "relationship":0, "power":0, "repetable":False, "image":"images/card_picture/ressourcecard.jpg" },
    {"name": "Chercher le collier d'immunité", "texte":"écriture", "health":-10, "food": 0, "materials":0, "relationship":-20, "power":0, "repetable":True, "image":"images/card_picture/placeholder.png" },
    {"name": "Danser autour du feu", "texte":"écriture", "health":0, "food": 0, "materials":0, "relationship":0, "power":0, "repetable":True, "image":"images/card_picture/placeholder.png" },
    {"name": "Construire un bâteau", "texte":"écriture", "health":0, "food": 0, "materials":-25, "relationship":0, "power":25, "repetable":False, "image":"images/card_picture/powercard.jpg" },
    {"name": "Construire une canne à pêche", "texte":"écriture", "health":0, "food": 10, "materials":-10, "relationship":0, "power":0, "repetable":False, "image":"images/card_picture/foodcard.jpg" },
    {"name": "Organiser un tour de garde", "texte":"écriture", "health":-10, "food": 0, "materials":0, "relationship":-20, "power":0, "repetable":True, "image":"images/card_picture/placeholder.png" },
    {"name": "Explorer les marais", "texte":"écriture", "health":0, "food": 0, "materials":10, "relationship":0, "power":0, "repetable":True, "image":"images/card_picture/ressourcecard.jpg" },
    {"name": "Récolter des algues", "texte":"écriture", "health":0, "food": 10, "materials":0, "relationship":0, "power":0, "repetable":True, "image":"images/card_picture/foodcard.jpg" },
    {"name": "S'aventurer à marée basse", "texte":"écriture", "health":0, "food": 0, "materials":10, "relationship":0, "power":0, "repetable":True, "image":"images/card_picture/ressourcecard.jpg" },
    {"name": "Gravir la montagne", "texte":"écriture", "health":-10, "food": 0, "materials":10, "relationship":0, "power":0, "repetable":True, "image":"images/card_picture/ressourcecard.jpg" },
    {"name": "Créer une dispute volontaire", "texte":"écriture", "health":0, "food": 0, "materials":10, "relationship":-20, "power":-5, "repetable":True, "image":"images/card_picture/ressourcecard.jpg" },
    {"name": "Soigner un survivant malade", "texte":"écriture", "health":0, "food": -20, "materials":-10, "relationship":10, "power":0, "repetable":True, "image":"images/card_picture/relationshipcard.jpg" },
    {"name": "Manifester contre la mondialisation", "texte":"écriture", "health":0, "food": 0, "materials":0, "relationship":0, "power":0, "repetable":False, "image":"images/card_picture/placeholder.png" },
    {"name": "Cueillir des herbes médicinales", "texte":"écriture", "health":0, "food": 0, "materials":10, "relationship":0, "power":0, "repetable":True, "image":"images/card_picture/ressourcecard.jpg" },
    {"name": "Instaurer un jour férié", "texte":"écriture", "health":0, "food": 0, "materials":0, "relationship":0, "power":0, "repetable":False, "image":"images/card_picture/placeholder.png" },
    {"name": "Fêter Noël", "texte":"écriture", "health":15, "food": -10, "materials":-10, "relationship":20, "power":0, "repetable":False, "image":"images/card_picture/relationshipcard.jpg" },
    {"name": "Manifester contre les cheminots", "texte":"écriture", "health":0, "food": 0, "materials":0, "relationship":0, "power":0, "repetable":False, "image":"images/card_picture/placeholder.png" },
    {"name": "Essayer une nouvelle recette", "texte":"écriture", "health":0, "food": 10, "materials":-10, "relationship":0, "power":0, "repetable":True, "image":"images/card_picture/foodcard.jpg" },
    {"name": "Organiser une chasse au trésor", "texte":"écriture", "health":0, "food": 0, "materials":10, "relationship":10, "power":0, "repetable":False, "image":"images/card_picture/placeholder.png" },
    {"name": "Mais c'étais sur enfait", "texte":"écriture", "health":-50, "food": 0, "materials":0, "relationship":0, "power":0, "repetable":False, "image":"images/card_picture/placeholder.png" },
    {"name": "Sardoche et l'elo boost", "texte":"écriture", "health":0, "food": 0, "materials":0, "relationship":0, "power":0, "repetable":False, "image":"images/card_picture/placeholder.png" },
    {"name": "Manger jonquille ?", "texte":"écriture", "health":0, "food": 20, "materials":0, "relationship":0, "power":0, "repetable":False, "image":"images/card_picture/foodcard.jpg" }








]

#Carte 2 à 81 